//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.EmployeeRoles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.EmployeeRoles.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee roles.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string ErrorName1 {
            get {
                return ResourceManager.GetString("ErrorName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 3 characters long..
        /// </summary>
        public static string ErrorName2 {
            get {
                return ResourceManager.GetString("ErrorName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 50 characters..
        /// </summary>
        public static string ErrorName3 {
            get {
                return ResourceManager.GetString("ErrorName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This permission is required..
        /// </summary>
        public static string ErrorPermission1 {
            get {
                return ResourceManager.GetString("ErrorPermission1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role power must be a positive number..
        /// </summary>
        public static string ErrorRolePower1 {
            get {
                return ResourceManager.GetString("ErrorRolePower1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role power cannot exceed 999..
        /// </summary>
        public static string ErrorRolePower2 {
            get {
                return ResourceManager.GetString("ErrorRolePower2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage employees.
        /// </summary>
        public static string ManageEmployees {
            get {
                return ResourceManager.GetString("ManageEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage leaves.
        /// </summary>
        public static string ManageLeaves {
            get {
                return ResourceManager.GetString("ManageLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage rentals.
        /// </summary>
        public static string ManageRentals {
            get {
                return ResourceManager.GetString("ManageRentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage schedule.
        /// </summary>
        public static string ManageSchedule {
            get {
                return ResourceManager.GetString("ManageSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage vehicles.
        /// </summary>
        public static string ManageVehicles {
            get {
                return ResourceManager.GetString("ManageVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role power.
        /// </summary>
        public static string RolePower {
            get {
                return ResourceManager.GetString("RolePower", resourceCulture);
            }
        }
    }
}
