//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.Vehicles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.Vehicles.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mileage.
        /// </summary>
        public static string CurrentMileage {
            get {
                return ResourceManager.GetString("CurrentMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom daily rate.
        /// </summary>
        public static string CustomDailyRate {
            get {
                return ResourceManager.GetString("CustomDailyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom deposit.
        /// </summary>
        public static string CustomDeposit {
            get {
                return ResourceManager.GetString("CustomDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom weekly rate.
        /// </summary>
        public static string CustomWeeklyRate {
            get {
                return ResourceManager.GetString("CustomWeeklyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available?.
        /// </summary>
        public static string DataGridAvailable {
            get {
                return ResourceManager.GetString("DataGridAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily rate.
        /// </summary>
        public static string DataGridCustomDailyRate {
            get {
                return ResourceManager.GetString("DataGridCustomDailyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string DataGridCustomDeposit {
            get {
                return ResourceManager.GetString("DataGridCustomDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly rate.
        /// </summary>
        public static string DataGridCustomWeeklyRate {
            get {
                return ResourceManager.GetString("DataGridCustomWeeklyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color field is required..
        /// </summary>
        public static string ErrorColor1 {
            get {
                return ResourceManager.GetString("ErrorColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mileage must be a positive number..
        /// </summary>
        public static string ErrorCurrentMileage1 {
            get {
                return ResourceManager.GetString("ErrorCurrentMileage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mileage is required..
        /// </summary>
        public static string ErrorCurrentMileage2 {
            get {
                return ResourceManager.GetString("ErrorCurrentMileage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom daily rate must be a positive number..
        /// </summary>
        public static string ErrorCustomDailyRate1 {
            get {
                return ResourceManager.GetString("ErrorCustomDailyRate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom deposit must be a positive number..
        /// </summary>
        public static string ErrorCustomDeposit1 {
            get {
                return ResourceManager.GetString("ErrorCustomDeposit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom weekly rate must be a positive number..
        /// </summary>
        public static string ErrorCustomWeeklyRate1 {
            get {
                return ResourceManager.GetString("ErrorCustomWeeklyRate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last maintenance date must be a valid date..
        /// </summary>
        public static string ErrorLastMaintenanceDate1 {
            get {
                return ResourceManager.GetString("ErrorLastMaintenanceDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last maintenance mileage must be a positivie number..
        /// </summary>
        public static string ErrorLastMaintenanceMileage1 {
            get {
                return ResourceManager.GetString("ErrorLastMaintenanceMileage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate field is required..
        /// </summary>
        public static string ErrorLicensePlate1 {
            get {
                return ResourceManager.GetString("ErrorLicensePlate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate field cannot exceed 20 characters..
        /// </summary>
        public static string ErrorLicensePlate2 {
            get {
                return ResourceManager.GetString("ErrorLicensePlate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year must be a valid year..
        /// </summary>
        public static string ErrorManufactureYear1 {
            get {
                return ResourceManager.GetString("ErrorManufactureYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year is required..
        /// </summary>
        public static string ErrorManufactureYear2 {
            get {
                return ResourceManager.GetString("ErrorManufactureYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next maintenance date must be a valid date..
        /// </summary>
        public static string ErrorNextMaintenanceDate1 {
            get {
                return ResourceManager.GetString("ErrorNextMaintenanceDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes cannot exceed 500 characters..
        /// </summary>
        public static string ErrorNotes1 {
            get {
                return ResourceManager.GetString("ErrorNotes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date must be a valid date..
        /// </summary>
        public static string ErrorPurchaseDate1 {
            get {
                return ResourceManager.GetString("ErrorPurchaseDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date field is required..
        /// </summary>
        public static string ErrorPurchaseDate2 {
            get {
                return ResourceManager.GetString("ErrorPurchaseDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price must be a positive number..
        /// </summary>
        public static string ErrorPurchasePrice1 {
            get {
                return ResourceManager.GetString("ErrorPurchasePrice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price is required..
        /// </summary>
        public static string ErrorPurchasePrice2 {
            get {
                return ResourceManager.GetString("ErrorPurchasePrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental place is required..
        /// </summary>
        public static string ErrorRentalPlace1 {
            get {
                return ResourceManager.GetString("ErrorRentalPlace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle status is required..
        /// </summary>
        public static string ErrorStatus1 {
            get {
                return ResourceManager.GetString("ErrorStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle model is required..
        /// </summary>
        public static string ErrorVehicleModel1 {
            get {
                return ResourceManager.GetString("ErrorVehicleModel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle type is required..
        /// </summary>
        public static string ErrorVehicleType1 {
            get {
                return ResourceManager.GetString("ErrorVehicleType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN is required..
        /// </summary>
        public static string ErrorVin1 {
            get {
                return ResourceManager.GetString("ErrorVin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN must have 17 characters..
        /// </summary>
        public static string ErrorVin2 {
            get {
                return ResourceManager.GetString("ErrorVin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air conditioning.
        /// </summary>
        public static string HasAirConditioning {
            get {
                return ResourceManager.GetString("HasAirConditioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic transmission.
        /// </summary>
        public static string HasAutomaticTransmission {
            get {
                return ResourceManager.GetString("HasAutomaticTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        public static string HasBluetooth {
            get {
                return ResourceManager.GetString("HasBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise control.
        /// </summary>
        public static string HasCruiseControl {
            get {
                return ResourceManager.GetString("HasCruiseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string HasNavigation {
            get {
                return ResourceManager.GetString("HasNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking sensors.
        /// </summary>
        public static string HasParkingSensors {
            get {
                return ResourceManager.GetString("HasParkingSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string IsAvailableForRent {
            get {
                return ResourceManager.GetString("IsAvailableForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last maintenance date.
        /// </summary>
        public static string LastMaintenanceDate {
            get {
                return ResourceManager.GetString("LastMaintenanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last maintenance mileage.
        /// </summary>
        public static string LastMaintenanceMileage {
            get {
                return ResourceManager.GetString("LastMaintenanceMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate.
        /// </summary>
        public static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year.
        /// </summary>
        public static string ManufactureYear {
            get {
                return ResourceManager.GetString("ManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next maintenance date.
        /// </summary>
        public static string NextMaintenanceDate {
            get {
                return ResourceManager.GetString("NextMaintenanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Information.
        /// </summary>
        public static string OptionalInfoFields {
            get {
                return ResourceManager.GetString("OptionalInfoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental place.
        /// </summary>
        public static string RentalPlace {
            get {
                return ResourceManager.GetString("RentalPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rental Place.
        /// </summary>
        public static string SelectRentalPlace {
            get {
                return ResourceManager.GetString("SelectRentalPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vehicle Model.
        /// </summary>
        public static string SelectVehicleModel {
            get {
                return ResourceManager.GetString("SelectVehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vehicle Status.
        /// </summary>
        public static string SelectVehicleStatus {
            get {
                return ResourceManager.GetString("SelectVehicleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vehicle Type.
        /// </summary>
        public static string SelectVehicleType {
            get {
                return ResourceManager.GetString("SelectVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string VehicleStatus {
            get {
                return ResourceManager.GetString("VehicleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
    }
}
