//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.VehicleTypes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.VehicleTypes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base daily rate.
        /// </summary>
        public static string BaseDailyRate {
            get {
                return ResourceManager.GetString("BaseDailyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base deposit.
        /// </summary>
        public static string BaseDeposit {
            get {
                return ResourceManager.GetString("BaseDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base weekly rate.
        /// </summary>
        public static string BaseWeeklyRate {
            get {
                return ResourceManager.GetString("BaseWeeklyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Types.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base daily rate must be a positive number..
        /// </summary>
        public static string ErrorBaseDailyRate1 {
            get {
                return ResourceManager.GetString("ErrorBaseDailyRate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base deposit must be a positive number..
        /// </summary>
        public static string ErrorBaseDeposit1 {
            get {
                return ResourceManager.GetString("ErrorBaseDeposit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base weekly rate must be a positive number..
        /// </summary>
        public static string ErrorBaseWeeklyRate1 {
            get {
                return ResourceManager.GetString("ErrorBaseWeeklyRate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 300 characters..
        /// </summary>
        public static string ErrorDescription1 {
            get {
                return ResourceManager.GetString("ErrorDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string ErrorName1 {
            get {
                return ResourceManager.GetString("ErrorName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must have at least 3 characters..
        /// </summary>
        public static string ErrorName2 {
            get {
                return ResourceManager.GetString("ErrorName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 30 characters..
        /// </summary>
        public static string ErrorName3 {
            get {
                return ResourceManager.GetString("ErrorName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required license field is mandatory..
        /// </summary>
        public static string ErrorRequiredLicenseType1 {
            get {
                return ResourceManager.GetString("ErrorRequiredLicenseType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required license must be a valid license..
        /// </summary>
        public static string ErrorRequiredLicenseType2 {
            get {
                return ResourceManager.GetString("ErrorRequiredLicenseType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required license type.
        /// </summary>
        public static string RequiredLicenseType {
            get {
                return ResourceManager.GetString("RequiredLicenseType", resourceCulture);
            }
        }
    }
}
