//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.VehicleModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.VehicleModels.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Models.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        public static string Electric {
            get {
                return ResourceManager.GetString("Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine size.
        /// </summary>
        public static string EngineSize {
            get {
                return ResourceManager.GetString("EngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 250 characters..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine size must be a number..
        /// </summary>
        public static string ErrorEngineSize {
            get {
                return ResourceManager.GetString("ErrorEngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type is required..
        /// </summary>
        public static string ErrorFuelType {
            get {
                return ResourceManager.GetString("ErrorFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse power must be a number..
        /// </summary>
        public static string ErrorHorsePower {
            get {
                return ResourceManager.GetString("ErrorHorsePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required and must be at least 3 characters long..
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand is required..
        /// </summary>
        public static string ErrorVehicleBrandId {
            get {
                return ResourceManager.GetString("ErrorVehicleBrandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse power.
        /// </summary>
        public static string HorsePower {
            get {
                return ResourceManager.GetString("HorsePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string Hybrid {
            get {
                return ResourceManager.GetString("Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string Petrol {
            get {
                return ResourceManager.GetString("Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select vehicle brand.
        /// </summary>
        public static string SelectVehicleBrandTitle {
            get {
                return ResourceManager.GetString("SelectVehicleBrandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle brand.
        /// </summary>
        public static string VehicleBrand {
            get {
                return ResourceManager.GetString("VehicleBrand", resourceCulture);
            }
        }
    }
}
