//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.Rentals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.Rentals.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage fee.
        /// </summary>
        public static string DamageFee {
            get {
                return ResourceManager.GetString("DamageFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee payment status.
        /// </summary>
        public static string DamageFeePaymentStatus {
            get {
                return ResourceManager.GetString("DamageFeePaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit deduction.
        /// </summary>
        public static string DepositDeduction {
            get {
                return ResourceManager.GetString("DepositDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit refund.
        /// </summary>
        public static string DepositRefundAmount {
            get {
                return ResourceManager.GetString("DepositRefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit status.
        /// </summary>
        public static string DepositStatus {
            get {
                return ResourceManager.GetString("DepositStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickups.
        /// </summary>
        public static string DisplayNamePickups {
            get {
                return ResourceManager.GetString("DisplayNamePickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string DisplayNameReturns {
            get {
                return ResourceManager.GetString("DisplayNameReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit deduction cannot be higher than deposit amount..
        /// </summary>
        public static string ErrorDepositDeduction1 {
            get {
                return ResourceManager.GetString("ErrorDepositDeduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string ErrorMarkingPickup {
            get {
                return ResourceManager.GetString("ErrorMarkingPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to mark a rent as picked up. Rent payment isn&apos;t complete..
        /// </summary>
        public static string ErrorMarkingPickupPaymentText {
            get {
                return ResourceManager.GetString("ErrorMarkingPickupPaymentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to mark a rent as picked up. Rent isn&apos;t waiting for pickup..
        /// </summary>
        public static string ErrorMarkingPickupText {
            get {
                return ResourceManager.GetString("ErrorMarkingPickupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final cost.
        /// </summary>
        public static string FinalCost {
            get {
                return ResourceManager.GetString("FinalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish date.
        /// </summary>
        public static string FinishDateTime {
            get {
                return ResourceManager.GetString("FinishDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is car damaged?.
        /// </summary>
        public static string IsCarDamaged {
            get {
                return ResourceManager.GetString("IsCarDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is car refueled?.
        /// </summary>
        public static string IsCarRefueled {
            get {
                return ResourceManager.GetString("IsCarRefueled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is customer late?.
        /// </summary>
        public static string IsCustomerLate {
            get {
                return ResourceManager.GetString("IsCustomerLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup date.
        /// </summary>
        public static string PickupDateTime {
            get {
                return ResourceManager.GetString("PickupDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Dates.
        /// </summary>
        public static string RentalDates {
            get {
                return ResourceManager.GetString("RentalDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started by.
        /// </summary>
        public static string StartedByEmployee {
            get {
                return ResourceManager.GetString("StartedByEmployee", resourceCulture);
            }
        }
    }
}
