//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.Payments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.Payments.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit refund.
        /// </summary>
        public static string DepositRefundAmount {
            get {
                return ResourceManager.GetString("DepositRefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is invalid..
        /// </summary>
        public static string ErrorAmount1 {
            get {
                return ResourceManager.GetString("ErrorAmount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required..
        /// </summary>
        public static string ErrorCustomer1 {
            get {
                return ResourceManager.GetString("ErrorCustomer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date is required..
        /// </summary>
        public static string ErrorPaymentDate1 {
            get {
                return ResourceManager.GetString("ErrorPaymentDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date is invalid..
        /// </summary>
        public static string ErrorPaymentDate2 {
            get {
                return ResourceManager.GetString("ErrorPaymentDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent is required..
        /// </summary>
        public static string ErrorRent1 {
            get {
                return ResourceManager.GetString("ErrorRent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail reason.
        /// </summary>
        public static string FailReason {
            get {
                return ResourceManager.GetString("FailReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund reason.
        /// </summary>
        public static string RefundReason {
            get {
                return ResourceManager.GetString("RefundReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        public static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rental.
        /// </summary>
        public static string SelectRental {
            get {
                return ResourceManager.GetString("SelectRental", resourceCulture);
            }
        }
    }
}
