//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.ParametrizeDocuments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.ParametrizeDocuments.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Variables:.
        /// </summary>
        public static string AvailableVariables {
            get {
                return ResourceManager.GetString("AvailableVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrize Document.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating document: .
        /// </summary>
        public static string ErrorDocument {
            get {
                return ResourceManager.GetString("ErrorDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Document.
        /// </summary>
        public static string GenerateDocument {
            get {
                return ResourceManager.GetString("GenerateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Not Selected.
        /// </summary>
        public static string ModelNotSelected {
            get {
                return ResourceManager.GetString("ModelNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Selected.
        /// </summary>
        public static string ModelSelected {
            get {
                return ResourceManager.GetString("ModelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model selected..
        /// </summary>
        public static string NoModel {
            get {
                return ResourceManager.GetString("NoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select input and output files..
        /// </summary>
        public static string PleaseSelectFiles {
            get {
                return ResourceManager.GetString("PleaseSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model Type.
        /// </summary>
        public static string SelectModelType {
            get {
                return ResourceManager.GetString("SelectModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Path.
        /// </summary>
        public static string SelectOutputPath {
            get {
                return ResourceManager.GetString("SelectOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Template File.
        /// </summary>
        public static string SelectTemplateFile {
            get {
                return ResourceManager.GetString("SelectTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document generated successfuly..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
