//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.Generic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.Generic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created after:.
        /// </summary>
        public static string CreatedAfter {
            get {
                return ResourceManager.GetString("CreatedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created before:.
        /// </summary>
        public static string CreatedBefore {
            get {
                return ResourceManager.GetString("CreatedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Date.
        /// </summary>
        public static string DeletedDate {
            get {
                return ResourceManager.GetString("DeletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified after:.
        /// </summary>
        public static string ModifiedAfter {
            get {
                return ResourceManager.GetString("ModifiedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified before:.
        /// </summary>
        public static string ModifiedBefore {
            get {
                return ResourceManager.GetString("ModifiedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing .
        /// </summary>
        public static string PaginationShowing1 {
            get {
                return ResourceManager.GetString("PaginationShowing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  items per page..
        /// </summary>
        public static string PaginationShowing2 {
            get {
                return ResourceManager.GetString("PaginationShowing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total items: .
        /// </summary>
        public static string PaginationTotalItems {
            get {
                return ResourceManager.GetString("PaginationTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating a model..
        /// </summary>
        public static string USCreateError1 {
            get {
                return ResourceManager.GetString("USCreateError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating.
        /// </summary>
        public static string USCreateError2 {
            get {
                return ResourceManager.GetString("USCreateError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  created successfully..
        /// </summary>
        public static string USCreateSuccess {
            get {
                return ResourceManager.GetString("USCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting.
        /// </summary>
        public static string USDeleteError {
            get {
                return ResourceManager.GetString("USDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to delete..
        /// </summary>
        public static string USDeleteSelect {
            get {
                return ResourceManager.GetString("USDeleteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deleted successfully..
        /// </summary>
        public static string USDeleteSuccess {
            get {
                return ResourceManager.GetString("USDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to edit..
        /// </summary>
        public static string USEditSelect {
            get {
                return ResourceManager.GetString("USEditSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading models: .
        /// </summary>
        public static string USLoadError1 {
            get {
                return ResourceManager.GetString("USLoadError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while searching models: .
        /// </summary>
        public static string USLoadError2 {
            get {
                return ResourceManager.GetString("USLoadError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for .
        /// </summary>
        public static string USLoadSearchCompleted1 {
            get {
                return ResourceManager.GetString("USLoadSearchCompleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  completed .
        /// </summary>
        public static string USLoadSearchCompleted2 {
            get {
                return ResourceManager.GetString("USLoadSearchCompleted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string USLoadSearchCompleted3 {
            get {
                return ResourceManager.GetString("USLoadSearchCompleted3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing only deleted .
        /// </summary>
        public static string USLoadShowingDeleted {
            get {
                return ResourceManager.GetString("USLoadShowingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  loaded successfully..
        /// </summary>
        public static string USLoadSuccess {
            get {
                return ResourceManager.GetString("USLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to restore..
        /// </summary>
        public static string USRestoreSelect {
            get {
                return ResourceManager.GetString("USRestoreSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating.
        /// </summary>
        public static string USUpdateError {
            get {
                return ResourceManager.GetString("USUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to edit..
        /// </summary>
        public static string USUpdateSelect {
            get {
                return ResourceManager.GetString("USUpdateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  updated successfully..
        /// </summary>
        public static string USUpdateSuccess {
            get {
                return ResourceManager.GetString("USUpdateSuccess", resourceCulture);
            }
        }
    }
}
