//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.Employees {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.Employees.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Fields.
        /// </summary>
        public static string AddressFields {
            get {
                return ResourceManager.GetString("AddressFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base salary.
        /// </summary>
        public static string BaseSalary {
            get {
                return ResourceManager.GetString("BaseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information Fields.
        /// </summary>
        public static string BasicInformationFields {
            get {
                return ResourceManager.GetString("BasicInformationFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable base salary.
        /// </summary>
        public static string DisableBaseSalary {
            get {
                return ResourceManager.GetString("DisableBaseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable hourly rate.
        /// </summary>
        public static string DisableHourlyRate {
            get {
                return ResourceManager.GetString("DisableHourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Position.
        /// </summary>
        public static string EmployeePosition {
            get {
                return ResourceManager.GetString("EmployeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required..
        /// </summary>
        public static string ErrorDateOfBirth1 {
            get {
                return ResourceManager.GetString("ErrorDateOfBirth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth must be valid..
        /// </summary>
        public static string ErrorDateOfBirth2 {
            get {
                return ResourceManager.GetString("ErrorDateOfBirth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string ErrorEmail1 {
            get {
                return ResourceManager.GetString("ErrorEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be valid..
        /// </summary>
        public static string ErrorEmail2 {
            get {
                return ResourceManager.GetString("ErrorEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee position is required..
        /// </summary>
        public static string ErrorEmployeePosition1 {
            get {
                return ResourceManager.GetString("ErrorEmployeePosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string ErrorFirstName1 {
            get {
                return ResourceManager.GetString("ErrorFirstName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot exceed 50 characters..
        /// </summary>
        public static string ErrorFirstName2 {
            get {
                return ResourceManager.GetString("ErrorFirstName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire date is required..
        /// </summary>
        public static string ErrorHireDate1 {
            get {
                return ResourceManager.GetString("ErrorHireDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire date must be valid..
        /// </summary>
        public static string ErrorHireDate2 {
            get {
                return ResourceManager.GetString("ErrorHireDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string ErrorLastName1 {
            get {
                return ResourceManager.GetString("ErrorLastName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot exceed 50 characters..
        /// </summary>
        public static string ErrorLastName2 {
            get {
                return ResourceManager.GetString("ErrorLastName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string ErrorPhoneNumber1 {
            get {
                return ResourceManager.GetString("ErrorPhoneNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number cannot exceed 20 characters..
        /// </summary>
        public static string ErrorPhoneNumber2 {
            get {
                return ResourceManager.GetString("ErrorPhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental place is required..
        /// </summary>
        public static string ErrorRentalPlace1 {
            get {
                return ResourceManager.GetString("ErrorRentalPlace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person cannot be a supervisor..
        /// </summary>
        public static string ErrorSupervisor1 {
            get {
                return ResourceManager.GetString("ErrorSupervisor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination date must be valid..
        /// </summary>
        public static string ErrorTerminationDate1 {
            get {
                return ResourceManager.GetString("ErrorTerminationDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finances Fields.
        /// </summary>
        public static string FinancesFields {
            get {
                return ResourceManager.GetString("FinancesFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire date.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate.
        /// </summary>
        public static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental place.
        /// </summary>
        public static string RentalPlace {
            get {
                return ResourceManager.GetString("RentalPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country.
        /// </summary>
        public static string SelectCountryTitle {
            get {
                return ResourceManager.GetString("SelectCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a employee position.
        /// </summary>
        public static string SelectEmployeePositionTitle {
            get {
                return ResourceManager.GetString("SelectEmployeePositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position.
        /// </summary>
        public static string SelectPosition {
            get {
                return ResourceManager.GetString("SelectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rental Place.
        /// </summary>
        public static string SelectRentalPlace {
            get {
                return ResourceManager.GetString("SelectRentalPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a rental place.
        /// </summary>
        public static string SelectRentalPlaceTitle {
            get {
                return ResourceManager.GetString("SelectRentalPlaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Supervisor.
        /// </summary>
        public static string SelectSupervisor {
            get {
                return ResourceManager.GetString("SelectSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a supervisor.
        /// </summary>
        public static string SelectSupervisorTitle {
            get {
                return ResourceManager.GetString("SelectSupervisorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination date.
        /// </summary>
        public static string TerminationDate {
            get {
                return ResourceManager.GetString("TerminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
