//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Resources.RentalRequests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Resources.RentalRequests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Requests.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required..
        /// </summary>
        public static string ErrorCustomer1 {
            get {
                return ResourceManager.GetString("ErrorCustomer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is required..
        /// </summary>
        public static string ErrorEndDate1 {
            get {
                return ResourceManager.GetString("ErrorEndDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is invalid..
        /// </summary>
        public static string ErrorEndDate2 {
            get {
                return ResourceManager.GetString("ErrorEndDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be before start date..
        /// </summary>
        public static string ErrorEndDate3 {
            get {
                return ResourceManager.GetString("ErrorEndDate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request date is required..
        /// </summary>
        public static string ErrorRequestDate1 {
            get {
                return ResourceManager.GetString("ErrorRequestDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request date is invalid..
        /// </summary>
        public static string ErrorRequestDate2 {
            get {
                return ResourceManager.GetString("ErrorRequestDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required..
        /// </summary>
        public static string ErrorStartDate1 {
            get {
                return ResourceManager.GetString("ErrorStartDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is invalid..
        /// </summary>
        public static string ErrorStartDate2 {
            get {
                return ResourceManager.GetString("ErrorStartDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be after end date..
        /// </summary>
        public static string ErrorStartDate3 {
            get {
                return ResourceManager.GetString("ErrorStartDate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is required..
        /// </summary>
        public static string ErrorVehicle1 {
            get {
                return ResourceManager.GetString("ErrorVehicle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        public static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vehicle.
        /// </summary>
        public static string SelectVehicle {
            get {
                return ResourceManager.GetString("SelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental cost.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
    }
}
